version: '3.7'

services:

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/:/var/lib/mysql/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 33066:3306
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      - ./:/app
    depends_on:
      - mysql
    links:
      - mysql

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      - ./:/app
    depends_on:
      - mysql
    links:
      - mysql

  

      